@startuml

title 业务方接入支付系统流程

participant "业务端前端" as 前段 #gray
participant "业务端服务端" as 业务服务端 #gray
participant "支付平台收银台SDK/H5页面" as SDK
participant "支付平台" as 支付平台
participant "第三方支付" as 外部 #green

前段 -> 业务服务端 : 创建支付订单
业务服务端 -> 支付平台 : 创建支付单
支付平台 --> 业务服务端 : 返回支付单
业务服务端 --> 前段:返回支付参数

前段 -> SDK: 使用支付参数调起支付SDK
SDK -> 支付平台 :请求收银台页面信息
支付平台 --> SDK: 返回收银台页面信息
SDK -> 支付平台 :发起支付请求
支付平台 --> SDK: 返回URL/支付参数
SDK -> 外部 : 根据URL/支付参数跳转第三方支付服务支付
外部 --> SDK : 同步返回
SDK --> 前段 : 同步返回

外部 --> 支付平台 : 异步通知支付结果
支付平台 --> 业务服务端: 异步通知支付结果
前段 -> 业务服务端 : 查询支付结果
业务服务端 -> 前段 : 返回结果



@enduml