@startuml

title 支付系统内部流程

participant "业务系统后端&前端" as 业务系统 #gray
box "支付系统" #LightBlue
participant "收银台" as 收银台
participant "交易系统" as 支付
participant "账务系统" as 账务
participant "网关系统" as 网关
end box

participant "第三方支付系统/银行" as 第三方 #green

==下单==
业务系统 -> 业务系统:创建业务单
业务系统 -> 支付 : 发起支付请求
支付 -> 支付 : 创建交易单
支付 --> 业务系统 : 返回交易单
业务系统 -> 收银台 : 跳转到收银台
收银台 -> 支付:获取收银台列表

支付 -> 网关 : 根据请求来源[业务接入方,PC,iOS等]配置信息，\n拉取支持的支付方式
网关 --> 支付 : 返回支持的支付方式信息

支付 --> 收银台 : 返回收银台列表

==支付==
alt 选择的是，第三方平台支付[微信，支付宝]
收银台 -> 支付 : 选择支付方式
支付 -> 支付 : 创建支付单[处理中]
支付 -> 网关 : 请求支付
网关 -> 网关 : 创建网关支付单[处理中]
网关 -> 第三方 : 请求预支付
第三方 --> 网关 : 返回预支付信息
网关 -> 网关 :回写第三方支付信息
网关 --> 支付 : 返回网关支付信息
支付 --> 收银台 :返回
收银台 -> 第三方 :跳转到第三方支付APP
第三方 -> 第三方: 用户在第三方APP内支付
第三方 --> 业务系统:跳转到支付结果页面
end

==第三方回调==
'alt 第三方回调
第三方 --> 网关 : 支付结果回调
网关 -> 网关 :网关支付单结果更新
网关 --> 支付:回调，支付单状态更新
'else 定时主动查询
'支付->网关:查询支付状态
'第三方 -> 网关
'网关 -->第三方
'网关-->支付:返回状态
'end
支付 -> 账务 :记账
支付 -> 支付: 更新交易单状态
支付 --> 业务系统: 回调通知
业务系统 -> 业务系统:更新订单

newpage

==定时查询==
支付->网关:查询支付状态
网关 ->第三方
第三方 --> 网关
网关-->支付:返回状态
支付 -> 账务 :记账
支付 -> 支付: 更新交易单状态
支付 --> 业务系统: 回调通知
业务系统 -> 业务系统:更新订单


==业务系统轮询==
业务系统 -> 支付: 查询订单支付状态
支付 --> 业务系统: 返回订单支付状态




@enduml